<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pl" xml:lang="pl">
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headScript(); ?>
    </head>
    <body>
        <div id="gfwb">
            <ul id="gfwb-left">
                <li>Stargate</li>
                <li class="active">Stargate</li>
                <li>Stargate</li>
                <li>Stargate</li>
                <li>Stargate</li>                
                <li>Progamela</li>
            </ul>
            <ul id="gfwb-right">
                <?php if ($this->user == true): ?>
                    <li><?php echo $this->user->user_personal ?></li>
                    <li><?php echo $this->user->thumb(20,20) ?></li>
                    <li>Logout</li>
                <?php else: ?>
                    <li>Sign in</li>
                    <li>Sign up</li>
                <?php endif; ?>
            </ul>
        </div>
        <div id="page">
            <div class="container">
                <?php echo $this->layout()->content; ?>
            </div>
        </div>
    </body>
</html>
