<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pl" xml:lang="pl">
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headScript(); ?>
    </head>
    <body>
        <script>
            $(function(){
                var width = Number($('#gfwblhb').attr('iw'));
                $('#gfwbl').hover(function(){
                    $('#gfwblhb').animate({'width':width,'opacity':1},{'queue': false});
                },function(){
                    $('#gfwblhb').animate({'width':0,'opacity':0},{'queue': false});
                });
                
                $('#gfwblhb').click(function(){
                    $('#gfwbl').animate({'width': iw},{'queue': false});
                });
                
                $('#gfwblsb.hide').click(function(){
                    $('#gfwbl').show("slide", { direction: "right" }, 2000);
                });
            });
        </script>
        <div id="gfwb">
            <ul id="gfwbl">
                <li><a href="">Stargate</a></li>
                <li class="active"><a href="">Stargate</a></li>
                <li><a href="">Stargate</a></li>
                <li><a href="">Stargate</a></li>
                <li><a href="">Stargate</a></li>
                <li id="gfwblhb" iw="25"><a href="#">hide</a></li>
            </ul>
            <ul id="gfwbr">
                <?php if ($this->user == true): ?>
                    
                <?php else: ?>
                    <li><a href="">Sign in</a></li>
                <?php endif; ?>
            </ul>
        </div>
        <div id="page">
            <div class="container">
                <?php echo $this->layout()->content; ?>
            </div>
        </div>
    </body>
</html>
