<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pl" xml:lang="pl">
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headScript(); ?>
    </head>
    <body>
        <script>
            $(document).ready(function(){
                $('#gfwbl').hover(function(){
                    var width = number($('#gfwblhb img').width());
                    if(width < 1) { width = '32px'; }
                    $('#gfwblhb').animate('width',width);
                },function(){
                    $('#gfwblhb').animate('width',0);
                });
            });
        </script>
        <div id="gfwb">
            <ul id="gfwbl">
                <li><a href="">Stargate</a></li>
                <li class="active"><a href="">Stargate</a></li>
                <li><a href="">Stargate</a></li>
                <li><a href="">Stargate</a></li>
                <li><a href="">Stargate</a></li>
                <li id="gfwblhb"><a href="#"><img src="/img/gfwb_hide-left.png" alt="hide" /></a></li>
            </ul>
            <ul id="gfwbr">
                <?php if ($this->user == true): ?>
                    
                <?php else: ?>
                    <li><a href="">Sign in</a></li>
                <?php endif; ?>
            </ul>
        </div>
        <div id="page">
            <div class="container">
                <?php echo $this->layout()->content; ?>
            </div>
        </div>
    </body>
</html>
